[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "secwexen-arsenal"
description = "Personal a cybersecurity toolkit featuring defensive security and blue team tools built with Python, Bash, Shell, and PowerShell."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }

authors = [
    { name = "secwexen" }
]

keywords = [
    "python",
    "cybersecurity",
    "cybersecurity-tools",
    "defensive-security",
    "portfolio",
    "blue-team",
    "bash",
    "shell",
    "powershell",
    "osint",
]

classifiers = [
  "Intended Audience :: Information Technology",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Operating System :: OS Independent",
  "Topic :: Security"
]

dependencies = [
    "requests",
    "aiohttp",
    "rich",
    "colorama",
    "typer",
    "python-dotenv",
    "pydantic",
    "beautifulsoup4",
    "lxml",
    "pandas",
    "cryptography>=46.0.5",
    "dnspython",
    "python-whois",
    "shodan",
    "tqdm"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "black",
    "isort",
    "flake8",
    "pylint",
    "mypy",
    "bandit",
    "pre-commit"
]

[project.urls]
Homepage = "https://secwexen.github.io/"
Repository = "https://github.com/secwexen/secwexen-arsenal"

[project.entry-points.console_scripts]
secwexenarsenal = "secwexenarsenal.cli:main"

[tool.setuptools.packages.find]
where = ["."]
