name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please provide the details below.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      placeholder: Short description of the feature
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      placeholder: Explain the feature and how it should work
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      placeholder: Why is this feature needed?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      placeholder: Any alternative solutions or workarounds?

  - type: textarea
    id: additional
    attributes:
      label: Additional Notes
      placeholder: Any extra context or screenshots
